tidak valid


$cek_tdk_valid_siup == 1 && $cek_tdk_valid_kbli_siup == 1 && $cek_tdk_valid_nib == 1 && $cek_tdk_valid_kbli_nib && $cek_tdk_valid_sbu == 1 && $cek_tdk_valid_kbli_sbu && $cek_tdk_valid_siujk == 1 && $cek_tdk_valid_kbli_siujk == 1 && $cek_tdk_valid_akta_pendirian == 1 && $cek_tdk_valid_akta_perubahan && $cek_tdk_valid_pemilik == 1 && $cek_tdk_valid_pengurus == 1 && $cek_tdk_valid_pengalaman == 1 && $cek_tdk_valid_sppkp == 1 && $cek_tdk_valid_npwp == 1 && $cek_tdk_valid_spt == 1 && $cek_tdk_valid_neraca_keuangan == 1 && $cek_tdk_valid_keuangan == 1


valid
$cek_siup == 1 && $cek_kbli_siup == 1 && $cek_nib == 1 && $cek_kbli_nib && $cek_sbu == 1 && $cek_kbli_sbu && $cek_siujk == 1 && $cek_kbli_siujk == 1 && $cek_akta_pendirian == 1 && $cek_akta_perubahan && $cek_pemilik == 1 && $cek_pengurus == 1 && $cek_pengalaman == 1 && $cek_sppkp == 1 && $cek_npwp == 1 && $cek_spt == 1 && $cek_neraca_keuangan == 1 && $cek_keuangan == 1